<script lang="ts" setup>
  import CounterCard from '~/components/shared/CounterCard.vue'
  import type { HydraNode } from '~/interfaces/api/hydra-nodes/hydra-node.type'

  const nodes = ref<HydraNode[]>([
    {
      id: 1,
      description: 'Generated by party 1',
      port: 10000,
      vkey: '{"type":"HydraVerificationKey_ed25519","description":"","cborHex":"5820471763269340d0d1a06847aa19483a74b0755852be19aa85d6af0231d03f45e0"}',
      createdAt: '2024-12-22T16:23:07.879Z'
    },
    {
      id: 2,
      description: 'Generated by party 1',
      port: 10001,
      vkey: '{"type":"HydraVerificationKey_ed25519","description":"","cborHex":"582085d19e3337ff01cc876f69efc2a806400accc76258157cdefc349fee18676820"}',
      createdAt: '2024-12-22T16:23:07.879Z'
    },
    {
      id: 3,
      description: 'Generated by party 2',
      port: 10002,
      vkey: '{"type":"HydraVerificationKey_ed25519","description":"","cborHex":"58208cd1e0fbee18a74ec7b7f9c9abf867c1c0fab7df648c20a4aa494f454e72d047"}',
      createdAt: '2024-12-22T16:23:07.879Z'
    }
  ])
</script>

<template>
  <div class="">
    <el-row :gutter="16" class="h-30">
      <el-col :span="8" class="">
        <CounterCard title="Total nodes" :value="0" />
      </el-col>
      <el-col :span="8" class="">
        <CounterCard title="Running nodes" :value="0" />
      </el-col>
      <el-col :span="8" class="">
        <CounterCard title="Available nodes" :value="0" />
      </el-col>
    </el-row>
    <div class="mt-8">
      <div class="flex justify-between">
        <div class=""></div>
        <div class="flex">
          <el-button type="primary"> Create </el-button>
        </div>
      </div>
    </div>
    <div class="mt-4 grid grid-cols-3 gap-4">
      <HydraNodeCard v-for="node in nodes" :key="node.id" :node="node" />
    </div>
  </div>
</template>

<style lang="scss" scoped></style>
